### ISSUE TITLE
Error after error in nodejs 23.4.0: [TypeError: (intermediate value).get(...).replace is not a function]

### ISSUE THREAD

**Issue by dincerpece** [sindresorhus/file-type#703]
### Description

After migrating from nodejs 23.3.0 to 23.4.0, I encountered an error in my code. Your fileTypeFromBuffer function gives an error and does not return a value, and naturally my code stops working there. It does not pass to "console.log(fileType)" at all, it gives an error without even getting an empty value, and the fileTypeFromBuffer function stops working! While it worked fine in Node.js 23.3.0, this problem occurred in 23.4.0.

![fileTypeFromBuffer_error1](https://github.com/user-attachments/assets/b0b18dac-e95a-4b69-be91-e0e1a4c12877)
![fileTypeFromBuffer_error2](https://github.com/user-attachments/assets/e3457e43-5443-4181-ac17-2e35b458e61c)

### Existing Issue Check

- [X] I have searched the existing issues and could not find any related to my problem.

### ESM (ECMAScript Module) Requirement Acknowledgment

- [X] My project is an [ESM project](https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c) and my `package.json` contains the following entry: `"type": "module"`.

### File-Type Scope Acknowledgment

- [X] I understand that file-type detects binary file types and not text or other formats.

**Comment by Borewit** [comment]
I could not reproduce your issue @dincerpece:

```js
import { readFileSync } from 'node:fs';
import { fileTypeFromBuffer } from 'file-type';
import { versions } from 'process';

console.log(`Node.js version: ${versions.node}`);

const buffer = readFileSync('sample-gif-files-sample_640x426.gif');
const result = await fileTypeFromBuffer(buffer);
console.log(JSON.stringify(result));
```
Outputs:
```
Node.js version: 23.4.0
{"ext":"gif","mime":"image/gif"}
````

**Comment by Borewit** [comment]
I managed to reproduce the issue, use the previous code sample, parsing: [fixture.cr3](https://github.com/sindresorhus/file-type/blob/e99257d1e25a2d24f5c625ed879aaa4957e82799/fixture/fixture.cr3).

That outputs:
```
TypeError: (intermediate value).get(...).replace is not a function
    at FileTypeParser.parse (file:///C:/Users/Borewit/IdeaProjects/file-type/core.js:613:77)
```
which refers to:
https://github.com/sindresorhus/file-type/blob/e99257d1e25a2d24f5c625ed879aaa4957e82799/core.js#L613

**Comment by Borewit** [comment]
Looks like a bug in Node.js 23.4.0, in the TextDecoder.decode(): https://github.com/nodejs/node/issues/56219 

```js
const encoding = 'latin1';
const buffer = Buffer.from('Hello!', encoding); // Initializes: <Buffer 48 65 6c 6c 6f 21>
const textDecoder = new TextDecoder(encoding);
const decodedString = textDecoder.decode(buffer);
const returnType = typeof decodedString;
if (returnType === 'string') {
    console.log('Fine, we got a string, as expected');
} else {
    console.error('This is odd, we received an ' + returnType);
}
```

Outputs in 23.4.0:
```
This is odd, we received an object
```
