### ISSUE TITLE
Cannot find module 'strtok3/core' from 'node_modules/file-type/core.js'

### ISSUE THREAD

**Issue by Matthew-McRaven** [sindresorhus/file-type#548]
Hello,

I have version 17.1.2 installed in a project.

When I attempt to use this library I get the error `Cannot find module 'strtok3/core' from 'node_modules/file-type/core.js'`

This seems to be caused by core.js:3 referencing `strtok3/core` instead of `strtok3/lib/core`.

Maybe this is a problem with my local setup, but wanted to see if there was an easy resolution to this issue.

**Comment by marcegige** [comment]
@Matthew-McRaven I'm having the same issue, did you find a solution to it?

@sindresorhus is there any coming update to fix this?

**Comment by Matthew-McRaven** [comment]
I ended up forking the project and fixing the import paths.

**Comment by anton000** [comment]
@Matthew-McRaven  i think you should just do  a pull req on the package.json quick fix

**Comment by Matthew-McRaven** [comment]
@anton000, This isn't a package.json fix. You have to modify core.js:3 and fix the import path.

I'm not entirely confident that this error isn't an artifact of my build environment (yarn 3 using lerna in a monorepo), so I opted for a fork with the fixes.

The author of the project or another maintainer can replicate the bug in a less specialized environment, I'd happily submit a PR.

**Comment by Krankypanky** [comment]
also facing the same issue after updating from 16.4.0 to 17.1.4
```
api_1       | ERROR in ./node_modules/file-type/index.js
api_1       | Module not found: Error: Can't resolve 'strtok3' in '/code/node_modules/file-type'
api_1       | 
api_1       | ERROR in ./node_modules/file-type/core.js 681:28
api_1       | Module parse failed: Identifier directly after number (681:28)
api_1       | You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
api_1       | | 				while (children > 0) {
api_1       | | 					const element = await readElement();
api_1       | > 					if (element.id === 0x42_82) {
api_1       | | 						const rawValue = await tokenizer.readToken(new Token.StringType(element.len, 'utf-8'));
api_1       | | 						return rawValue.replace(/\00.*$/g, ''); // Return DocType
```

**Comment by Borewit** [comment]
file-type version 17 is an ES-Module, version 16 and below is CommonJS. If you do not run from an ESM project yourself, you can expect issues going from 16 to 17.

Related issues: #541, #515, #502 

See also: https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c

**Comment by Borewit** [comment]
The path 'strtok3/core' was wrong indeed, sorry issue was hard to distinct from the many basic ESM issues.
Issue fixed by:
 - #553

**Comment by Nases** [comment]
lib folder is missing on release 8.0.2, try downgrading to 8.0.1
issue -> [https://github.com/Borewit/strtok3/issues/1143](https://github.com/Borewit/strtok3/issues/1143)

**Comment by AnonymousSausage77** [comment]
Woah Nases, what a timely answer. That worked for me

**Comment by Borewit** [comment]
> lib folder is missing on strtok3 package `8.0.2`, try downgrading to `8.0.1` (this is a dependency of file-type) issue -> [Borewit/strtok3#1143](https://github.com/Borewit/strtok3/issues/1143)
> 
> You can confirm this by `ls node_modules/strtok3` and you might only see `LICENSE package.json README.md`, no source code exported.

Issue Borewit/strtok3#1143, has been resolved in [strtok3@8.0.3](https://github.com/Borewit/strtok3/releases/tag/v8.0.3)
