### ISSUE TITLE
Cant't resolve fs after updating to 13.0.3 version

### ISSUE THREAD

**Issue by spirosdi** [sindresorhus/file-type#304]
I am using file-type in an angular app. When running ng serve, I get the following:
ERROR in ./node_modules/strtok3/lib/FsPromise.js
Module not found: Error: Can't resolve 'fs' in /node_modules/strtok3/lib'
With v12 it works

**Comment by Borewit** [comment]
And you did include `file-type/browser` instead of `file-type` as described [here](https://github.com/sindresorhus/file-type#browser) @spirosdi?

**Comment by spirosdi** [comment]
ah right.. missing fs is now resolved. But I get a console error:
```
core.js:6014 ERROR Error: Uncaught (in promise): ReferenceError: process is not defined
ReferenceError: process is not defined
    at Object../node_modules/process-nextick-args/index.js (index.js:3)
```
Just by including file-type/browser

**Comment by Borewit** [comment]
Some of the Node modules need to be [_polyfilled_](https://en.wikipedia.org/wiki/Polyfill_(programming)) to work in the browser.

```
npm i process
```
In `polyfill.ts` add:

```ts
import * as process from 'process';
(window as any).process = process;
```

You may need to add `buffer` as well:
```
npm i buffer
```

In `polyfill.ts` add:
```ts
import * as _buffer from 'buffer';
(window as any).Buffer = _buffer.Buffer;
```

Example: [audio-tag-analyzer/blob/master/src/polyfills.ts](https://github.com/Borewit/audio-tag-analyzer/blob/master/src/polyfills.ts)
